chat_server:
    build: .
    working_dir: /app/ws-chat
    command: bash -c "godep restore && go build && ./ws-chat"
    #volumes:
    #    - .:/app/ws-chat
    expose:
        - "8080"
    #ports:
    #    - "8080:8080"

haproxy:
    image: tutum/haproxy
    expose:
        - "80"
    ports:
        - "8080:80"
    links:
        - chat_server:chat
    environment:
        - BACKEND_PORT=8080